name: Process PDF Files

on:
  workflow_dispatch:
    inputs:
      confidence:
        description: 'Confidence threshold (0-100)'
        required: false
        default: '65'
        type: number
      dpi:
        description: 'DPI for PDF processing (higher = better quality but slower)'
        required: false
        default: '200'
        type: number
      language:
        description: 'OCR language (e.g. eng, ita, fra, deu, spa)'
        required: false
        default: 'ita'
        type: string
  push:
    paths:
      - 'pdf_input/**'

jobs:
  rotate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Tesseract OCR and Poppler
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-${{ github.event.inputs.language || 'ita' }} poppler-utils
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Process PDF Files
        run: |
          mkdir -p pdf_output
          
          # Find PDF files in the input directory
          PDF_FILES=$(find pdf_input -name "*.pdf" -type f)
          
          if [ -z "$PDF_FILES" ]; then
            echo "Nessun file PDF trovato nella cartella pdf_input!"
            exit 0
          fi
          
          # Process each PDF file
          for PDF_FILE in $PDF_FILES; do
            echo "Elaborazione di $PDF_FILE"
            FILENAME=$(basename "$PDF_FILE")
            python auto_rotate_pdf.py "$PDF_FILE" -o "pdf_output/${FILENAME%.pdf}_corrected.pdf" -c ${{ github.event.inputs.confidence || '65' }} -d ${{ github.event.inputs.dpi || '200' }}
          done
      
      - name: Commit processed PDFs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pdf_output/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "Nessuna modifica da committare."
          else
            git commit -m "Add processed PDF files"
            git push
          fi
